[project]
name = "ai-snake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.0.1",
    "loguru>=0.7.3",
    "matplotlib>=3.10.1",
    "pygame>=2.6.1",
]
